export const DEPLOYMENT_MODES = ["local", "deployed"] as const;
export const AUTH_MODES = ["local", "sso"] as const;
export const AUTH_PROVIDERS = ["github", "google", "azure"] as const;
export const COMPANY_ROLES = ["admin", "user"] as const;
export const ORGANIZATION_INVITATION_STATUSES = [
  "pending",
  "accepted",
  "revoked",
  "expired",
] as const;
export const INVITATION_DELIVERY_STATUSES = [
  "not_configured",
  "pending",
  "sent",
  "failed_retryable",
  "failed_terminal",
  "suppressed",
] as const;
export const INVITATION_PROJECT_GRANT_STATUSES = [
  "pending",
  "applied",
  "revoked",
  "failed",
] as const;
export const PROJECT_INVITATION_OUTCOMES = ["invitation_pending", "membership_created"] as const;
export const PROJECT_ROLES = ["viewer", "editor", "admin"] as const;
export const PROJECT_MEMBER_SOURCES = ["direct", "company_admin", "local_personal"] as const;
export const PROJECT_STATUSES = ["active", "read_only", "disabled"] as const;
export const RETENTION_DATA_CLASSES = [
  "TRACES",
  "LOGS",
  "METRICS",
  "AI_EVALS",
  "DATASETS",
  "SCORERS",
  "DASHBOARD_HISTORY",
  "INGEST_CREDENTIAL_AUDIT",
] as const;
export const RETENTION_MODES = ["retain", "delete", "soft_delete_then_delete"] as const;
export const ALERT_RULE_KINDS = [
  "METRIC_THRESHOLD",
  "METRIC_ABSENCE",
  "LOG_MATCH",
  "LOG_COUNT",
  "TRACE_MATCH",
  "TRACE_COUNT",
  "TRACE_LATENCY",
  "TRACE_ERROR",
] as const;
export const ALERT_SEVERITIES = ["INFO", "WARNING", "ERROR", "CRITICAL"] as const;
export const ALERT_STATES = ["OK", "PENDING", "FIRING", "RESOLVED", "SILENCED", "ERROR"] as const;
export const AI_PROVIDER_KINDS = [
  "anthropic",
  "openai",
  "azure_foundry",
  "aws_bedrock",
  "openai_compatible",
] as const;
export const AI_MODEL_PURPOSES = [
  "default",
  "chat",
  "judge",
  "optimizer",
  "embedding",
  "replay",
] as const;
export const AI_CHAT_CONVERSATION_STATUSES = ["active", "archived"] as const;
export const AI_CHAT_RUN_STATUSES = [
  "idle",
  "queued",
  "streaming",
  "completed",
  "failed",
  "cancelled",
  "awaiting_approval",
] as const;
export const AI_CHAT_ACTION_RISKS = ["low", "medium", "high", "destructive"] as const;
export const AI_CHAT_ACTION_STATUSES = [
  "proposed",
  "approved",
  "rejected",
  "executing",
  "succeeded",
  "failed",
  "expired",
] as const;
export const AI_CHAT_ARTIFACT_KINDS = [
  "json_render",
  "data_file",
  "script",
  "script_output",
] as const;
export const AI_CHAT_STREAM_EVENT_TYPES = [
  "run.started",
  "message.created",
  "text.delta",
  "tool.started",
  "tool.completed",
  "artifact.created",
  "action.proposed",
  "compaction.started",
  "compaction.saved",
  "run.completed",
  "run.failed",
  "heartbeat",
] as const;

export const TELEMETRY_SUBJECTS = [
  "telemetry.traces.search",
  "telemetry.traces.get",
  "telemetry.logs.search",
  "telemetry.facets",
  "telemetry.metrics.names",
  "telemetry.metrics.query",
  "telemetry.metrics.rich_query",
  "telemetry.projects.overview",
  "telemetry.traces.live.start",
  "telemetry.traces.live.stop",
  "telemetry.traces.live.events.*.*",
  "telemetry.persisted.traces",
  "telemetry.ingest.traces",
  "telemetry.ingest.logs",
  "telemetry.ingest.metrics",
  "telemetry.ingest.ai_projections",
] as const;

export const CONTROL_PLANE_SUBJECTS = [
  "control.viewer.get",
  "control.organizations.list",
  "control.organizations.get",
  "control.projects.list",
  "control.projects.list_for_service",
  "control.projects.get",
  "control.projects.create",
  "control.projects.update",
  "control.projects.select",
  "control.members.list",
  "control.members.update",
  "control.members.remove",
  "control.invitations.list",
  "control.invitations.create",
  "control.invitations.resend",
  "control.invitations.revoke",
  "control.project_invitations.create",
  "control.ingest_credentials.list",
  "control.ingest_credentials.create",
  "control.ingest_credentials.revoke",
  "control.ai_settings.get",
  "control.ai_settings.update",
  "control.ai_providers.project.get",
  "control.ai_providers.project.update",
  "control.ai_providers.company.get",
  "control.ai_providers.company.update",
  "control.ai_provider_secrets.resolve",
  "control.ai_chat.history",
  "control.ai_chat.conversation.get",
  "control.ai_chat.conversation.create",
  "control.ai_chat.conversation.archive",
  "control.ai_chat.conversation.delete",
  "control.ai_chat.message.append",
  "control.ai_chat.run.create",
  "control.ai_chat.run.update",
  "control.ai_chat.run.finalize",
  "control.ai_chat.action.propose",
  "control.ai_chat.action.approve",
  "control.ai_chat.action.finish",
  "control.ai_chat.compaction.save",
  "control.project_status.snapshot",
  "control.project_status.changed",
  "control.dashboards.list",
  "control.dashboards.save",
  "control.dashboards.delete",
  "control.dashboard_pins.set",
  "control.dashboard_pins.reorder",
  "control.project_members.list",
  "control.project_members.update",
  "control.project_members.remove",
  "control.retention.get",
  "control.retention.update",
  "control.alert_rules.list",
  "control.alert_rules.create",
  "control.alert_rules.update",
  "control.alert_rules.delete",
  "control.alert_silences.list",
  "control.alert_silences.create",
  "control.alert_silences.delete",
  "control.alert_history.list",
  "control.alert_summary.get",
  "control.alert_history.record",
] as const;

export const STORAGE_MAINTENANCE_SUBJECTS = [
  "storage_maintenance.retention.execute_batch",
] as const;

export const ALERT_EVALUATOR_SUBJECTS = [
  "alert_evaluator.tick",
  "alert_evaluator.rules.evaluate",
  "alert_evaluator.notifications.dispatch",
] as const;

export const AI_EVAL_SUBJECTS = [
  "telemetry.ingest.ai_projections",
  "ai.persisted.projections",
  "eval.dataset.create",
  "eval.dataset.items.append",
  "eval.dataset.settings.update",
  "eval.dataset.item.promote",
  "eval.dataset.item.update",
  "eval.dataset.version.get",
  "eval.dataset.search",
  "eval.dataset.health",
  "eval.dataset.candidates.prepare",
  "eval.dataset.candidates.search",
  "eval.dataset.candidates.commit",
  "eval.dataset.import.prepare",
  "eval.dataset.import.commit",
  "eval.dataset.export.start",
  "eval.dataset.transfer.get",
  "eval.agent_runs.search",
  "eval.evaluation.create",
  "eval.evaluation.update",
  "eval.evaluation.search",
  "eval.evaluation.run.start",
  "eval.evaluation.run.cancel",
  "eval.evaluation.run.pause",
  "eval.evaluation.run.resume",
  "eval.evaluation.run.search",
  "eval.evaluation.run.get",
  "eval.results.search",
  "eval.results.persist",
  "eval.evaluation.comparison.create",
  "eval.evaluation.comparison.search",
  "eval.target.snapshot.create",
  "eval.target.snapshot.get",
  "eval.target.diff",
  "eval.optimization.start",
  "eval.optimization.search",
  "eval.optimization.get",
  "eval.target.promote",
  "eval.live.start",
  "eval.live.stop",
  "eval.live.events.*.*",
] as const;

export const MESSAGE_BRIDGE_SUBJECTS = [
  ...TELEMETRY_SUBJECTS,
  ...CONTROL_PLANE_SUBJECTS,
  ...STORAGE_MAINTENANCE_SUBJECTS,
  ...ALERT_EVALUATOR_SUBJECTS,
  ...AI_EVAL_SUBJECTS,
] as const;

export const CLOUDGRID_ENV_VARS = [
  "CLOUDGRID_AI_CHAT_AWS_REGION",
  "CLOUDGRID_AI_CHAT_AZURE_DEPLOYMENT",
  "CLOUDGRID_AI_CHAT_BASE_URL",
  "CLOUDGRID_AI_CHAT_CREDENTIAL_REF",
  "CLOUDGRID_AI_CHAT_ENABLED",
  "CLOUDGRID_AI_CHAT_HARNESS_MODE",
  "CLOUDGRID_AI_CHAT_MODEL",
  "CLOUDGRID_AI_CHAT_PROVIDER_KIND",
  "CLOUDGRID_AI_CHAT_SANDBOX_MAX_ARTIFACT_BYTES",
  "CLOUDGRID_AI_CHAT_SANDBOX_MAX_INPUT_BYTES",
  "CLOUDGRID_AI_CHAT_TRACING_ENABLED",
  "CLOUDGRID_AI_EVAL_ENABLED",
  "CLOUDGRID_AI_EVAL_HARNESS_URL",
  "CLOUDGRID_AI_EVAL_RUNNER_HEALTH_HOST",
  "CLOUDGRID_AI_EVAL_RUNNER_HEALTH_PORT",
  "CLOUDGRID_ALERT_EVALUATOR_HEALTH_HOST",
  "CLOUDGRID_ALERT_EVALUATOR_HEALTH_PORT",
  "CLOUDGRID_ALERT_EVALUATOR_INTERVAL_SECONDS",
  "CLOUDGRID_ALERT_EVALUATOR_PROJECT_DISCOVERY_ENABLED",
  "CLOUDGRID_ALERT_EVALUATOR_PROJECT_IDS",
  "CLOUDGRID_ALERT_NOTIFICATION_ADAPTERS",
  "CLOUDGRID_ALERT_WEBHOOK_TIMEOUT_SECONDS",
  "CLOUDGRID_AUTH_AUDIENCE",
  "CLOUDGRID_AUTH_AZURE_AUDIENCE",
  "CLOUDGRID_AUTH_AZURE_CLIENT_ID",
  "CLOUDGRID_AUTH_AZURE_CLIENT_SECRET",
  "CLOUDGRID_AUTH_AZURE_ISSUER",
  "CLOUDGRID_AUTH_AZURE_JWKS_URL",
  "CLOUDGRID_AUTH_AZURE_REDIRECT_URI",
  "CLOUDGRID_AUTH_COMPANY_ID",
  "CLOUDGRID_AUTH_GITHUB_CLIENT_ID",
  "CLOUDGRID_AUTH_GITHUB_CLIENT_SECRET",
  "CLOUDGRID_AUTH_GITHUB_REDIRECT_URI",
  "CLOUDGRID_AUTH_GOOGLE_AUDIENCE",
  "CLOUDGRID_AUTH_GOOGLE_CLIENT_ID",
  "CLOUDGRID_AUTH_GOOGLE_CLIENT_SECRET",
  "CLOUDGRID_AUTH_GOOGLE_ISSUER",
  "CLOUDGRID_AUTH_GOOGLE_JWKS_URL",
  "CLOUDGRID_AUTH_GOOGLE_REDIRECT_URI",
  "CLOUDGRID_AUTH_ISSUER",
  "CLOUDGRID_AUTH_JWKS_URL",
  "CLOUDGRID_AUTH_MODE",
  "CLOUDGRID_AUTH_PROVIDER",
  "CLOUDGRID_AUTH_PROVIDERS",
  "CLOUDGRID_BENCH_DEPLOYMENT_PROFILE",
  "CLOUDGRID_BENCH_ENVIRONMENT_ID",
  "CLOUDGRID_BENCH_GRAPHQL_URL",
  "CLOUDGRID_BENCH_IMAGE_TAG",
  "CLOUDGRID_BENCH_OTLP_BEARER_TOKEN",
  "CLOUDGRID_BENCH_OTLP_TRACES_URL",
  "CLOUDGRID_BENCH_REQUESTS",
  "CLOUDGRID_BENCH_REQUIRED",
  "CLOUDGRID_BFF_HOST",
  "CLOUDGRID_BFF_PORT",
  "CLOUDGRID_BUN_BUILDER_IMAGE",
  "CLOUDGRID_BUN_RUNTIME_IMAGE",
  "CLOUDGRID_CONTROL_PLANE_HEALTH_HOST",
  "CLOUDGRID_CONTROL_PLANE_HEALTH_PORT",
  "CLOUDGRID_DATASET_TRANSFER_DIR",
  "CLOUDGRID_DEPENDENCY_RECOVERY_MAX_BACKOFF_MS",
  "CLOUDGRID_DEPLOYMENT_MODE",
  "CLOUDGRID_DEV_BFF_URL",
  "CLOUDGRID_DEV_READY_TIMEOUT_MS",
  "CLOUDGRID_DEV_SHUTDOWN_GRACE_MS",
  "CLOUDGRID_ENABLE_BENCHMARKS",
  "CLOUDGRID_ENABLE_RESILIENCE_CHAOS_TESTS",
  "CLOUDGRID_ENABLE_SURREALDB_CONTROL_TESTS",
  "CLOUDGRID_ENABLE_SURREALDB_PLAN_TESTS",
  "CLOUDGRID_ENABLE_SURREALDB_RETENTION_TESTS",
  "CLOUDGRID_ENABLE_SURREALDB_STORAGE_WRITE_TESTS",
  "CLOUDGRID_FRONTEND_DEV_PORT",
  "CLOUDGRID_FRONTEND_SERVE_STATIC",
  "CLOUDGRID_FRONTEND_STATIC_DIR",
  "CLOUDGRID_GO_BUILDER_IMAGE",
  "CLOUDGRID_GO_RUNTIME_IMAGE",
  "CLOUDGRID_GRAPHQL_ENDPOINT",
  "CLOUDGRID_GRAPHQL_MAX_COMPLEXITY",
  "CLOUDGRID_GRAPHQL_MAX_DEPTH",
  "CLOUDGRID_GRAPHQL_RESPONSE_MEDIA_TYPE",
  "CLOUDGRID_HEALTH_CHECK_TIMEOUT_MS",
  "CLOUDGRID_HARNESS_ADAPTER_OTLP_ENDPOINT",
  "CLOUDGRID_IMAGE_GID",
  "CLOUDGRID_IMAGE_REGISTRY",
  "CLOUDGRID_IMAGE_TAG",
  "CLOUDGRID_IMAGE_UID",
  "CLOUDGRID_INTEGRATION_AI_EVAL_HARNESS_PORT",
  "CLOUDGRID_INTEGRATION_AI_EVAL_RUNNER_HEALTH_PORT",
  "CLOUDGRID_INTEGRATION_BFF_PORT",
  "CLOUDGRID_INTEGRATION_CONTROL_PLANE_HEALTH_PORT",
  "CLOUDGRID_INTEGRATION_NATS_MONITOR_PORT",
  "CLOUDGRID_INTEGRATION_NATS_PORT",
  "CLOUDGRID_INTEGRATION_OTLP_GRPC_PORT",
  "CLOUDGRID_INTEGRATION_OTLP_PORT",
  "CLOUDGRID_INTEGRATION_STORAGE_READ_HEALTH_PORT",
  "CLOUDGRID_INTEGRATION_STORAGE_WRITE_HEALTH_PORT",
  "CLOUDGRID_INTEGRATION_SURREALDB_PORT",
  "CLOUDGRID_INVITATION_EMAIL_FROM",
  "CLOUDGRID_INVITATION_EMAIL_MAX_ATTEMPTS",
  "CLOUDGRID_INVITATION_EMAIL_MODE",
  "CLOUDGRID_INVITATION_EMAIL_REPLY_TO",
  "CLOUDGRID_INVITATION_EMAIL_REQUIRE_DELIVERY",
  "CLOUDGRID_INVITATION_EMAIL_RETRY_BASE_SECONDS",
  "CLOUDGRID_INVITATION_EMAIL_SMTP_HOST",
  "CLOUDGRID_INVITATION_EMAIL_SMTP_PASSWORD",
  "CLOUDGRID_INVITATION_EMAIL_SMTP_PORT",
  "CLOUDGRID_INVITATION_EMAIL_SMTP_TIMEOUT_MS",
  "CLOUDGRID_INVITATION_EMAIL_SMTP_TLS",
  "CLOUDGRID_INVITATION_EMAIL_SMTP_USERNAME",
  "CLOUDGRID_LIVE_EVENT_BUFFER_SIZE",
  "CLOUDGRID_LIVE_MAX_SUBSCRIPTIONS",
  "CLOUDGRID_LOG_LEVEL",
  "CLOUDGRID_LOG_STATE_CHANGE_MIN_INTERVAL_MS",
  "CLOUDGRID_MESSAGE_BRIDGE_REQUEST_TIMEOUT_MS",
  "CLOUDGRID_NATS_IMAGE_TAG",
  "CLOUDGRID_NATS_MAX_PAYLOAD",
  "CLOUDGRID_NATS_MONITOR_PORT",
  "CLOUDGRID_NATS_OPERATION_FLUSH_TIMEOUT_MS",
  "CLOUDGRID_NATS_PORT",
  "CLOUDGRID_NATS_RECONNECT_MAX_ATTEMPTS",
  "CLOUDGRID_NATS_RECONNECT_WAIT_MS",
  "CLOUDGRID_NATS_URL",
  "CLOUDGRID_OTLP_BEARER_TOKEN",
  "CLOUDGRID_OTLP_ENDPOINT",
  "CLOUDGRID_OTLP_GRPC_ADDR",
  "CLOUDGRID_OTLP_GRPC_COMPRESSION",
  "CLOUDGRID_OTLP_GRPC_MAX_MESSAGE_BYTES",
  "CLOUDGRID_OTLP_GRPC_PORT",
  "CLOUDGRID_OTLP_HTTP_ADDR",
  "CLOUDGRID_OTLP_HTTP_PORT",
  "CLOUDGRID_OTLP_LOCAL_PROJECT_ID",
  "CLOUDGRID_OTLP_LOCAL_PROJECT_TOKENS",
  "CLOUDGRID_OTLP_MAX_LOGS_PER_REQUEST",
  "CLOUDGRID_OTLP_MAX_METRIC_POINTS_PER_REQUEST",
  "CLOUDGRID_OTLP_MAX_REQUEST_BYTES",
  "CLOUDGRID_OTLP_MAX_SPANS_PER_REQUEST",
  "CLOUDGRID_OTLP_PUBLISH_TIMEOUT_MS",
  "CLOUDGRID_PROJECT_API_KEY",
  "CLOUDGRID_PROJECT_ID",
  "CLOUDGRID_PROJECT_STATUS_CACHE_STALE_SECONDS",
  "CLOUDGRID_PROJECT_STATUS_CACHE_TTL_SECONDS",
  "CLOUDGRID_PROVIDER_SECRET_ENCRYPTION_KEY",
  "CLOUDGRID_PUBLIC_URL",
  "CLOUDGRID_RETENTION_BATCH_LIMIT",
  "CLOUDGRID_RETENTION_BATCH_SIZE",
  "CLOUDGRID_RETENTION_DAYS",
  "CLOUDGRID_RETENTION_LEASE_SECONDS",
  "CLOUDGRID_RETENTION_MODE",
  "CLOUDGRID_RETENTION_SCHEDULER_ENABLED",
  "CLOUDGRID_RETENTION_SCHEDULER_INTERVAL_SECONDS",
  "CLOUDGRID_RETENTION_SCHEDULER_PROJECT_IDS",
  "CLOUDGRID_RUNTIME_STARTUP_DEPENDENCY_MODE",
  "CLOUDGRID_SELF_OBSERVABILITY_COMPANY_ID",
  "CLOUDGRID_SELF_OBSERVABILITY_ENABLED",
  "CLOUDGRID_SELF_OBSERVABILITY_EXPORT_FAILURE_LOG_LEVEL",
  "CLOUDGRID_SELF_OBSERVABILITY_EXPORT_INTERVAL_SECONDS",
  "CLOUDGRID_SELF_OBSERVABILITY_LOGS_ENABLED",
  "CLOUDGRID_SELF_OBSERVABILITY_METRICS_ENABLED",
  "CLOUDGRID_SELF_OBSERVABILITY_OTLP_BEARER_TOKEN",
  "CLOUDGRID_SELF_OBSERVABILITY_OTLP_ENDPOINT",
  "CLOUDGRID_SELF_OBSERVABILITY_PROJECT_ID",
  "CLOUDGRID_SELF_OBSERVABILITY_TRACES_ENABLED",
  "CLOUDGRID_SERVICE_MAX_IN_FLIGHT_REQUESTS",
  "CLOUDGRID_SESSION_SECRET",
  "CLOUDGRID_SESSION_TTL_SECONDS",
  "CLOUDGRID_STORAGE_ADAPTER",
  "CLOUDGRID_STORAGE_MAINTENANCE_HEALTH_HOST",
  "CLOUDGRID_STORAGE_MAINTENANCE_HEALTH_PORT",
  "CLOUDGRID_STORAGE_READ_HEALTH_HOST",
  "CLOUDGRID_STORAGE_READ_HEALTH_PORT",
  "CLOUDGRID_STORAGE_READ_MAX_METRIC_POINTS",
  "CLOUDGRID_STORAGE_READ_MAX_PAGE_SIZE",
  "CLOUDGRID_STORAGE_READ_QUERY_TIMEOUT_MS",
  "CLOUDGRID_STORAGE_WRITE_ACK_WAIT_SECONDS",
  "CLOUDGRID_STORAGE_WRITE_CONCURRENCY",
  "CLOUDGRID_STORAGE_WRITE_CONSUMER_MODE",
  "CLOUDGRID_STORAGE_WRITE_HEALTH_HOST",
  "CLOUDGRID_STORAGE_WRITE_HEALTH_PORT",
  "CLOUDGRID_STORAGE_WRITE_MAX_ACK_PENDING",
  "CLOUDGRID_STORAGE_WRITE_MAX_DELIVER",
  "CLOUDGRID_STORAGE_WRITE_PULL_BATCH_SIZE",
  "CLOUDGRID_STORAGE_WRITE_PULL_MAX_WAIT_MS",
  "CLOUDGRID_SURREALDB_CONNECT_TIMEOUT_MS",
  "CLOUDGRID_SURREALDB_DATABASE",
  "CLOUDGRID_SURREALDB_IMAGE_TAG",
  "CLOUDGRID_SURREALDB_NAMESPACE",
  "CLOUDGRID_SURREALDB_PASSWORD",
  "CLOUDGRID_SURREALDB_PORT",
  "CLOUDGRID_SURREALDB_READINESS_TIMEOUT_MS",
  "CLOUDGRID_SURREALDB_RECONNECT_ENABLED",
  "CLOUDGRID_SURREALDB_URL",
  "CLOUDGRID_SURREALDB_USERNAME",
  "VITE_CLOUDGRID_AI_CHAT_ENABLED",
  "VITE_CLOUDGRID_AI_EVAL_ENABLED",
  "VITE_CLOUDGRID_DEPLOYMENT_MODE",
  "VITE_CLOUDGRID_GRAPHQL_URL",
] as const;

export const CONTRACT_GENERATION_TARGETS = [
  "apps/packages/ui-contracts/src/generated.ts",
  "core/go-contracts/generated_contracts.go",
  "specs/03-contracts/messages/message-bridge.asyncapi.yaml",
] as const;

export type DeploymentMode = (typeof DEPLOYMENT_MODES)[number];
export type AuthMode = (typeof AUTH_MODES)[number];
export type AuthProvider = (typeof AUTH_PROVIDERS)[number];
export type CompanyRole = (typeof COMPANY_ROLES)[number];
export type OrganizationInvitationStatus = (typeof ORGANIZATION_INVITATION_STATUSES)[number];
export type InvitationDeliveryStatus = (typeof INVITATION_DELIVERY_STATUSES)[number];
export type InvitationProjectGrantStatus = (typeof INVITATION_PROJECT_GRANT_STATUSES)[number];
export type ProjectInvitationOutcome = (typeof PROJECT_INVITATION_OUTCOMES)[number];
export type ProjectRole = (typeof PROJECT_ROLES)[number];
export type ProjectMemberSource = (typeof PROJECT_MEMBER_SOURCES)[number];
export type ProjectStatus = (typeof PROJECT_STATUSES)[number];
export type RetentionDataClass = (typeof RETENTION_DATA_CLASSES)[number];
export type RetentionMode = (typeof RETENTION_MODES)[number];
export type AlertRuleKind = (typeof ALERT_RULE_KINDS)[number];
export type AlertSeverity = (typeof ALERT_SEVERITIES)[number];
export type AlertState = (typeof ALERT_STATES)[number];
export type TelemetrySubject = (typeof TELEMETRY_SUBJECTS)[number];
export type ControlPlaneSubject = (typeof CONTROL_PLANE_SUBJECTS)[number];
export type StorageMaintenanceSubject = (typeof STORAGE_MAINTENANCE_SUBJECTS)[number];
export type AlertEvaluatorSubject = (typeof ALERT_EVALUATOR_SUBJECTS)[number];
export type AiEvalSubject = (typeof AI_EVAL_SUBJECTS)[number];
export type MessageBridgeSubject = (typeof MESSAGE_BRIDGE_SUBJECTS)[number];
export type CloudGridEnvVar = (typeof CLOUDGRID_ENV_VARS)[number];
