//go:build surrealdb

package surrealdb

import (
	"context"
	"strings"
)

type SchemaQueryer interface {
	Query(ctx context.Context, sql string, vars map[string]any) error
}

func Initialize(ctx context.Context, db SchemaQueryer) error {
	return db.Query(ctx, SchemaSQL(), map[string]any{})
}

func SchemaSQL() string {
	return strings.Join(Statements(), ";\n") + ";"
}

func Statements() []string {
	statements := []string{
		"DEFINE TABLE IF NOT EXISTS trace SCHEMAFULL TYPE NORMAL",
		"DEFINE FIELD IF NOT EXISTS tenantId ON trace TYPE string",
		"DEFINE FIELD IF NOT EXISTS companyId ON trace TYPE string",
		"DEFINE FIELD IF NOT EXISTS projectId ON trace TYPE string",
		"DEFINE FIELD IF NOT EXISTS traceId ON trace TYPE string",
		"DEFINE FIELD IF NOT EXISTS serviceName ON trace TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS operationName ON trace TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS startedAt ON trace TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS startedAtUnixNano ON trace TYPE string",
		"DEFINE FIELD IF NOT EXISTS endedAt ON trace TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS endedAtUnixNano ON trace TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS durationNano ON trace TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS durationMs ON trace TYPE option<number>",
		"DEFINE FIELD IF NOT EXISTS rootSpanId ON trace TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS status ON trace TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS attributes ON trace TYPE object FLEXIBLE",
		"DEFINE FIELD IF NOT EXISTS spanCount ON trace TYPE int",
		"DEFINE FIELD IF NOT EXISTS errorSpanCount ON trace TYPE int",
		"DEFINE FIELD IF NOT EXISTS logCount ON trace TYPE int",
		"DEFINE FIELD IF NOT EXISTS serviceCount ON trace TYPE int",
		"DEFINE FIELD IF NOT EXISTS deletedAt ON trace TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS deletedByRetentionPolicyId ON trace TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS finalDeleteAfter ON trace TYPE option<datetime>",
		"DEFINE INDEX IF NOT EXISTS idx_trace_startedAt ON trace FIELDS startedAt",
		"DEFINE INDEX IF NOT EXISTS idx_trace_tenant_project_startedAt ON trace FIELDS tenantId, projectId, startedAt",
		"DEFINE INDEX IF NOT EXISTS idx_trace_tenant_project_traceId ON trace FIELDS tenantId, projectId, traceId",
		"DEFINE INDEX IF NOT EXISTS idx_trace_tenant_company_project_startedAt ON trace FIELDS tenantId, companyId, projectId, startedAt",
		"DEFINE INDEX IF NOT EXISTS idx_trace_tenant_company_project_traceId ON trace FIELDS tenantId, companyId, projectId, traceId",
		"DEFINE INDEX IF NOT EXISTS idx_trace_tenant_company_project_service_started ON trace FIELDS tenantId, companyId, projectId, serviceName, startedAt",
		"DEFINE INDEX IF NOT EXISTS idx_trace_tenant_company_project_status_started ON trace FIELDS tenantId, companyId, projectId, status, startedAt",
		"DEFINE INDEX IF NOT EXISTS idx_trace_serviceName ON trace FIELDS serviceName",
		"DEFINE INDEX IF NOT EXISTS idx_trace_status ON trace FIELDS status",

		"DEFINE TABLE IF NOT EXISTS span SCHEMAFULL TYPE NORMAL",
		"DEFINE FIELD IF NOT EXISTS tenantId ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS companyId ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS projectId ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS spanId ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS traceId ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS parentSpanId ON span TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS name ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS kind ON span TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS serviceName ON span TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS startedAt ON span TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS startedAtUnixNano ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS endedAt ON span TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS endedAtUnixNano ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS durationNano ON span TYPE string",
		"DEFINE FIELD IF NOT EXISTS durationMs ON span TYPE number",
		"DEFINE FIELD IF NOT EXISTS status ON span TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS attributes ON span TYPE object FLEXIBLE",
		"DEFINE FIELD OVERWRITE events ON span TYPE array<object>",
		"DEFINE FIELD OVERWRITE events[*].name ON span TYPE string",
		"DEFINE FIELD OVERWRITE events[*].timestamp ON span TYPE datetime",
		"DEFINE FIELD OVERWRITE events[*].timestampUnixNano ON span TYPE string",
		"DEFINE FIELD OVERWRITE events[*].attributes ON span TYPE object FLEXIBLE",
		"DEFINE FIELD OVERWRITE links ON span TYPE array<object>",
		"DEFINE FIELD OVERWRITE links[*].traceId ON span TYPE string",
		"DEFINE FIELD OVERWRITE links[*].spanId ON span TYPE string",
		"DEFINE FIELD OVERWRITE links[*].traceState ON span TYPE option<string>",
		"DEFINE FIELD OVERWRITE links[*].attributes ON span TYPE object FLEXIBLE",
		"DEFINE FIELD IF NOT EXISTS deletedAt ON span TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS deletedByRetentionPolicyId ON span TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS finalDeleteAfter ON span TYPE option<datetime>",
		"DEFINE INDEX IF NOT EXISTS idx_span_traceId ON span FIELDS traceId",
		"DEFINE INDEX IF NOT EXISTS idx_span_parentSpanId ON span FIELDS parentSpanId",
		"DEFINE INDEX IF NOT EXISTS idx_span_tenant_company_project_trace_parent_started ON span FIELDS tenantId, companyId, projectId, traceId, parentSpanId, startedAt",
		"DEFINE INDEX IF NOT EXISTS idx_span_tenant_company_project_service_trace ON span FIELDS tenantId, companyId, projectId, serviceName, traceId",
		"DEFINE INDEX IF NOT EXISTS idx_span_serviceName ON span FIELDS serviceName",
		"DEFINE INDEX IF NOT EXISTS idx_span_name ON span FIELDS name",
		"DEFINE INDEX IF NOT EXISTS idx_span_status ON span FIELDS status",

		"DEFINE TABLE IF NOT EXISTS log_event SCHEMAFULL TYPE NORMAL",
		"DEFINE FIELD IF NOT EXISTS tenantId ON log_event TYPE string",
		"DEFINE FIELD IF NOT EXISTS companyId ON log_event TYPE string",
		"DEFINE FIELD IF NOT EXISTS projectId ON log_event TYPE string",
		"DEFINE FIELD IF NOT EXISTS logEventId ON log_event TYPE string",
		"DEFINE FIELD IF NOT EXISTS traceId ON log_event TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS spanId ON log_event TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS serviceName ON log_event TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS severityText ON log_event TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS severityNumber ON log_event TYPE option<int>",
		"DEFINE FIELD IF NOT EXISTS body ON log_event TYPE any",
		"DEFINE FIELD IF NOT EXISTS bodyText ON log_event TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS timestamp ON log_event TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS observedTimestamp ON log_event TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS attributes ON log_event TYPE object FLEXIBLE",
		"DEFINE FIELD IF NOT EXISTS deletedAt ON log_event TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS deletedByRetentionPolicyId ON log_event TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS finalDeleteAfter ON log_event TYPE option<datetime>",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_timestamp ON log_event FIELDS timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_tenant_project_timestamp ON log_event FIELDS tenantId, projectId, timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_tenant_company_project_timestamp ON log_event FIELDS tenantId, companyId, projectId, timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_serviceName ON log_event FIELDS serviceName",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_tenant_project_serviceName ON log_event FIELDS tenantId, projectId, serviceName",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_tenant_company_project_service_timestamp ON log_event FIELDS tenantId, companyId, projectId, serviceName, timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_traceId ON log_event FIELDS traceId",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_tenant_company_project_trace_timestamp ON log_event FIELDS tenantId, companyId, projectId, traceId, timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_spanId ON log_event FIELDS spanId",
		"DEFINE INDEX IF NOT EXISTS idx_log_event_severityText ON log_event FIELDS severityText",

		"DEFINE TABLE IF NOT EXISTS metric_descriptor SCHEMAFULL TYPE NORMAL",
		"DEFINE FIELD IF NOT EXISTS tenantId ON metric_descriptor TYPE string",
		"DEFINE FIELD IF NOT EXISTS companyId ON metric_descriptor TYPE string",
		"DEFINE FIELD IF NOT EXISTS projectId ON metric_descriptor TYPE string",
		"DEFINE FIELD IF NOT EXISTS metricName ON metric_descriptor TYPE string",
		"DEFINE FIELD IF NOT EXISTS description ON metric_descriptor TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS unit ON metric_descriptor TYPE string",
		"DEFINE FIELD IF NOT EXISTS kind ON metric_descriptor TYPE string",
		"DEFINE FIELD IF NOT EXISTS aggregationTemporality ON metric_descriptor TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS monotonic ON metric_descriptor TYPE option<bool>",
		"DEFINE FIELD IF NOT EXISTS attributeKeys ON metric_descriptor TYPE array<string>",
		"DEFINE FIELD IF NOT EXISTS firstSeenAt ON metric_descriptor TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS lastSeenAt ON metric_descriptor TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS deletedAt ON metric_descriptor TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS deletedByRetentionPolicyId ON metric_descriptor TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS finalDeleteAfter ON metric_descriptor TYPE option<datetime>",
		"DEFINE INDEX IF NOT EXISTS idx_metric_descriptor_metricName ON metric_descriptor FIELDS metricName",
		"DEFINE INDEX IF NOT EXISTS idx_metric_descriptor_lastSeenAt ON metric_descriptor FIELDS lastSeenAt",
		"DEFINE INDEX IF NOT EXISTS idx_metric_descriptor_tenant_company_project_lastSeenAt ON metric_descriptor FIELDS tenantId, companyId, projectId, lastSeenAt",
		"DEFINE INDEX IF NOT EXISTS idx_metric_descriptor_tenant_company_project_metricName ON metric_descriptor FIELDS tenantId, companyId, projectId, metricName",

		"DEFINE TABLE IF NOT EXISTS metric_point SCHEMAFULL TYPE NORMAL",
		"DEFINE FIELD IF NOT EXISTS tenantId ON metric_point TYPE string",
		"DEFINE FIELD IF NOT EXISTS companyId ON metric_point TYPE string",
		"DEFINE FIELD IF NOT EXISTS projectId ON metric_point TYPE string",
		"DEFINE FIELD IF NOT EXISTS metricName ON metric_point TYPE string",
		"DEFINE FIELD IF NOT EXISTS serviceName ON metric_point TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS scopeName ON metric_point TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS kind ON metric_point TYPE string",
		"DEFINE FIELD IF NOT EXISTS timestamp ON metric_point TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS startTimestamp ON metric_point TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS value ON metric_point TYPE option<number>",
		"DEFINE FIELD IF NOT EXISTS count ON metric_point TYPE option<number>",
		"DEFINE FIELD IF NOT EXISTS sum ON metric_point TYPE option<number>",
		"DEFINE FIELD IF NOT EXISTS min ON metric_point TYPE option<number>",
		"DEFINE FIELD IF NOT EXISTS max ON metric_point TYPE option<number>",
		"DEFINE FIELD IF NOT EXISTS bucketCounts ON metric_point TYPE array<number>",
		"DEFINE FIELD IF NOT EXISTS explicitBounds ON metric_point TYPE array<number>",
		"DEFINE FIELD IF NOT EXISTS quantileValues ON metric_point TYPE array<object>",
		"DEFINE FIELD IF NOT EXISTS attributes ON metric_point TYPE object FLEXIBLE",
		"DEFINE FIELD OVERWRITE exemplars ON metric_point TYPE array<object>",
		"DEFINE FIELD OVERWRITE exemplars[*].timestamp ON metric_point TYPE datetime",
		"DEFINE FIELD OVERWRITE exemplars[*].value ON metric_point TYPE number",
		"DEFINE FIELD OVERWRITE exemplars[*].traceId ON metric_point TYPE option<string>",
		"DEFINE FIELD OVERWRITE exemplars[*].spanId ON metric_point TYPE option<string>",
		"DEFINE FIELD OVERWRITE exemplars[*].attributes ON metric_point TYPE object FLEXIBLE",
		"DEFINE FIELD IF NOT EXISTS droppedAttributeCount ON metric_point TYPE int",
		"DEFINE FIELD IF NOT EXISTS deletedAt ON metric_point TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS deletedByRetentionPolicyId ON metric_point TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS finalDeleteAfter ON metric_point TYPE option<datetime>",
		"DEFINE INDEX IF NOT EXISTS idx_metric_point_metricName ON metric_point FIELDS metricName",
		"DEFINE INDEX IF NOT EXISTS idx_metric_point_metricName_timestamp ON metric_point FIELDS metricName, timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_metric_point_tenant_company_project_metric_timestamp ON metric_point FIELDS tenantId, companyId, projectId, metricName, timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_metric_point_serviceName_timestamp ON metric_point FIELDS serviceName, timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_metric_point_tenant_company_project_service_timestamp ON metric_point FIELDS tenantId, companyId, projectId, serviceName, timestamp",
		"DEFINE INDEX IF NOT EXISTS idx_metric_point_timestamp ON metric_point FIELDS timestamp",

		"DEFINE TABLE IF NOT EXISTS metric_ingest_cardinality SCHEMAFULL TYPE NORMAL",
		"DEFINE FIELD IF NOT EXISTS tenantId ON metric_ingest_cardinality TYPE string",
		"DEFINE FIELD IF NOT EXISTS companyId ON metric_ingest_cardinality TYPE string",
		"DEFINE FIELD IF NOT EXISTS projectId ON metric_ingest_cardinality TYPE string",
		"DEFINE FIELD IF NOT EXISTS metricName ON metric_ingest_cardinality TYPE string",
		"DEFINE FIELD IF NOT EXISTS windowStart ON metric_ingest_cardinality TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS attributeKeys ON metric_ingest_cardinality TYPE array<string>",
		"DEFINE FIELD IF NOT EXISTS valueCounts ON metric_ingest_cardinality TYPE object FLEXIBLE",
		"DEFINE FIELD IF NOT EXISTS deletedAt ON metric_ingest_cardinality TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS deletedByRetentionPolicyId ON metric_ingest_cardinality TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS finalDeleteAfter ON metric_ingest_cardinality TYPE option<datetime>",
		"DEFINE INDEX IF NOT EXISTS idx_metric_ingest_cardinality_metricName_windowStart ON metric_ingest_cardinality FIELDS metricName, windowStart",

		"DEFINE TABLE IF NOT EXISTS service SCHEMAFULL TYPE NORMAL",
		"DEFINE FIELD IF NOT EXISTS tenantId ON service TYPE string",
		"DEFINE FIELD IF NOT EXISTS companyId ON service TYPE string",
		"DEFINE FIELD IF NOT EXISTS projectId ON service TYPE string",
		"DEFINE FIELD IF NOT EXISTS name ON service TYPE string",
		"DEFINE FIELD IF NOT EXISTS firstSeenAt ON service TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS lastSeenAt ON service TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS attributes ON service TYPE object FLEXIBLE",

		"DEFINE TABLE IF NOT EXISTS ingest_command SCHEMAFULL TYPE NORMAL",
		"DEFINE FIELD IF NOT EXISTS tenantId ON ingest_command TYPE string",
		"DEFINE FIELD IF NOT EXISTS companyId ON ingest_command TYPE string",
		"DEFINE FIELD IF NOT EXISTS projectId ON ingest_command TYPE string",
		"DEFINE FIELD IF NOT EXISTS commandId ON ingest_command TYPE string",
		"DEFINE FIELD IF NOT EXISTS source ON ingest_command TYPE string",
		"DEFINE FIELD IF NOT EXISTS requestId ON ingest_command TYPE string",
		"DEFINE FIELD IF NOT EXISTS subject ON ingest_command TYPE string",
		"DEFINE FIELD IF NOT EXISTS traceCount ON ingest_command TYPE int",
		"DEFINE FIELD IF NOT EXISTS spanCount ON ingest_command TYPE int",
		"DEFINE FIELD IF NOT EXISTS logCount ON ingest_command TYPE int",
		"DEFINE FIELD IF NOT EXISTS metricPointCount ON ingest_command TYPE int",
		"DEFINE FIELD IF NOT EXISTS completedAt ON ingest_command TYPE datetime",
		"DEFINE FIELD IF NOT EXISTS deletedAt ON ingest_command TYPE option<datetime>",
		"DEFINE FIELD IF NOT EXISTS deletedByRetentionPolicyId ON ingest_command TYPE option<string>",
		"DEFINE FIELD IF NOT EXISTS finalDeleteAfter ON ingest_command TYPE option<datetime>",
		"DEFINE INDEX IF NOT EXISTS idx_ingest_command_commandId ON ingest_command FIELDS commandId UNIQUE",
		"DEFINE INDEX IF NOT EXISTS idx_ingest_command_completedAt ON ingest_command FIELDS completedAt",
	}

	for _, table := range []string{
		"ai_agent_run",
		"ai_llm_call",
		"ai_tool_call",
		"ai_retrieval_event",
		"ai_dataset",
		"ai_dataset_item",
		"ai_scorer",
		"ai_eval_result",
		"ai_experiment",
		"ai_experiment_run",
		"ai_dataset_item_run",
		"ai_prompt_version",
		"ai_annotation_queue_item",
	} {
		statements = append(statements,
			"DEFINE TABLE IF NOT EXISTS "+table+" SCHEMAFULL TYPE NORMAL",
			"REMOVE FIELD IF EXISTS id ON "+table,
			"REMOVE INDEX IF EXISTS idx_"+table+"_tenant_project_id ON "+table,
			"DEFINE FIELD IF NOT EXISTS tenantId ON "+table+" TYPE string",
			"DEFINE FIELD IF NOT EXISTS companyId ON "+table+" TYPE string",
			"DEFINE FIELD IF NOT EXISTS projectId ON "+table+" TYPE string",
			"DEFINE FIELD IF NOT EXISTS traceId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS spanId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS experimentRunId ON "+table+" TYPE option<string>",
			"DEFINE FIELD OVERWRITE payload ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD IF NOT EXISTS name ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS description ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS kind ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS status ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS reviewStatus ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS split ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS rootSpanId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS inputDigest ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS outputDigest ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS agentRunId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS subKind ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS provider ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS requestModel ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS responseModel ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS toolName ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS toolCallId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS parametersDigest ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS resultDigest ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS embeddingModel ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS datasetId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS experimentId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS datasetItemId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS harnessRunId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS scorerId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS judgeModelRef ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS judgeRunRef ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS targetKind ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS targetId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS targetTraceId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS targetSpanId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS sourceTraceId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS sourceSpanId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS annotationQueueItemId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS resolvedDatasetItemId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS reason ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS assignedTo ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS hash ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS tag ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS text ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS notes ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS sourceFlavor ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS version ON "+table+" TYPE option<int>",
			"DEFINE FIELD IF NOT EXISTS datasetVersion ON "+table+" TYPE option<int>",
			"DEFINE FIELD IF NOT EXISTS scorerVersion ON "+table+" TYPE option<int>",
			"DEFINE FIELD IF NOT EXISTS itemCount ON "+table+" TYPE option<int>",
			"DEFINE FIELD IF NOT EXISTS documentCount ON "+table+" TYPE option<int>",
			"DEFINE FIELD IF NOT EXISTS topK ON "+table+" TYPE option<int>",
			"DEFINE FIELD IF NOT EXISTS latencyMs ON "+table+" TYPE option<number>",
			"DEFINE FIELD IF NOT EXISTS durationMs ON "+table+" TYPE option<number>",
			"DEFINE FIELD IF NOT EXISTS score ON "+table+" TYPE option<number>",
			"DEFINE FIELD IF NOT EXISTS passed ON "+table+" TYPE option<bool>",
			"DEFINE FIELD IF NOT EXISTS synthetic ON "+table+" TYPE option<bool>",
			"DEFINE FIELD OVERWRITE agent ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE costEstimate ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE definition ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE solverRef ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE summary ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE variableSchema ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD IF NOT EXISTS input ON "+table+" TYPE any",
			"DEFINE FIELD IF NOT EXISTS expected ON "+table+" TYPE any",
			"DEFINE FIELD IF NOT EXISTS output ON "+table+" TYPE any",
			"DEFINE FIELD OVERWRITE metadata ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE evidence ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE tokenTotals ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE tokenDetails ON "+table+" TYPE option<object> FLEXIBLE",
			"DEFINE FIELD OVERWRITE tags ON "+table+" TYPE option<array<string>>",
			"DEFINE FIELD OVERWRITE scorerIds ON "+table+" TYPE option<array<string>>",
			"DEFINE FIELD OVERWRITE evalResultIds ON "+table+" TYPE option<array<string>>",
			"DEFINE FIELD OVERWRITE messageEventIds ON "+table+" TYPE option<array<string>>",
			"DEFINE FIELD OVERWRITE documentDigests ON "+table+" TYPE option<array<string>>",
			"DEFINE FIELD OVERWRITE transcript ON "+table+" TYPE option<array<object>>",
			"DEFINE FIELD OVERWRITE transcript[*] ON "+table+" TYPE object FLEXIBLE",
			"DEFINE FIELD OVERWRITE llmCalls ON "+table+" TYPE option<array<object>>",
			"DEFINE FIELD OVERWRITE llmCalls[*] ON "+table+" TYPE object FLEXIBLE",
			"DEFINE FIELD OVERWRITE toolCalls ON "+table+" TYPE option<array<object>>",
			"DEFINE FIELD OVERWRITE toolCalls[*] ON "+table+" TYPE object FLEXIBLE",
			"DEFINE FIELD OVERWRITE retrievalEvents ON "+table+" TYPE option<array<object>>",
			"DEFINE FIELD OVERWRITE retrievalEvents[*] ON "+table+" TYPE object FLEXIBLE",
			"DEFINE FIELD OVERWRITE evalResults ON "+table+" TYPE option<array<object>>",
			"DEFINE FIELD OVERWRITE evalResults[*] ON "+table+" TYPE object FLEXIBLE",
			"DEFINE FIELD OVERWRITE itemRuns ON "+table+" TYPE option<array<object>>",
			"DEFINE FIELD OVERWRITE itemRuns[*] ON "+table+" TYPE object FLEXIBLE",
			"DEFINE FIELD OVERWRITE results ON "+table+" TYPE option<array<object>>",
			"DEFINE FIELD OVERWRITE results[*] ON "+table+" TYPE object FLEXIBLE",
			"DEFINE FIELD OVERWRITE normalizationWarnings ON "+table+" TYPE option<array<string>>",
			"DEFINE FIELD IF NOT EXISTS createdAt ON "+table+" TYPE option<datetime>",
			"DEFINE FIELD IF NOT EXISTS startedAt ON "+table+" TYPE option<datetime>",
			"DEFINE FIELD IF NOT EXISTS endedAt ON "+table+" TYPE option<datetime>",
			"DEFINE FIELD IF NOT EXISTS producedAt ON "+table+" TYPE option<datetime>",
			"DEFINE FIELD IF NOT EXISTS persistedAt ON "+table+" TYPE option<datetime>",
			"DEFINE FIELD IF NOT EXISTS deletedAt ON "+table+" TYPE option<datetime>",
			"DEFINE FIELD IF NOT EXISTS deletedByRetentionPolicyId ON "+table+" TYPE option<string>",
			"DEFINE FIELD IF NOT EXISTS finalDeleteAfter ON "+table+" TYPE option<datetime>",
			"DEFINE INDEX IF NOT EXISTS idx_"+table+"_tenant_project_traceId ON "+table+" FIELDS tenantId, projectId, traceId",
			"DEFINE INDEX IF NOT EXISTS idx_"+table+"_tenant_project_experimentRunId ON "+table+" FIELDS tenantId, projectId, experimentRunId",
		)
	}

	return statements
}
