package surrealdb

import (
	"strings"

	contracts "github.com/cloudgrid-dev/cloudgrid/core/go-contracts"
)

type QueryStatement struct {
	SQL    string
	Params map[string]any
}

func BuildSchemaStatements() []string {
	return []string{
		"DEFINE TABLE IF NOT EXISTS organization SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS name ON organization TYPE string;",
		"DEFINE FIELD IF NOT EXISTS slug ON organization TYPE string;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON organization TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON organization TYPE datetime;",
		"DEFINE INDEX IF NOT EXISTS organization_slug ON organization FIELDS slug UNIQUE;",
		"DEFINE TABLE IF NOT EXISTS user SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS displayName ON user TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS email ON user TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON user TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON user TYPE datetime;",
		"DEFINE TABLE IF NOT EXISTS project SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS organizationId ON project TYPE string;",
		"DEFINE FIELD IF NOT EXISTS name ON project TYPE string;",
		"DEFINE FIELD IF NOT EXISTS slug ON project TYPE string;",
		"DEFINE FIELD IF NOT EXISTS status ON project TYPE string;",
		"DEFINE FIELD IF NOT EXISTS changedAt ON project TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON project TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON project TYPE datetime;",
		"DEFINE INDEX IF NOT EXISTS project_organization_slug ON project FIELDS organizationId, slug UNIQUE;",
		"DEFINE INDEX IF NOT EXISTS project_organization_status ON project FIELDS organizationId, status;",
		"DEFINE TABLE IF NOT EXISTS membership TYPE RELATION IN user OUT organization SCHEMAFULL;",
		"DEFINE FIELD IF NOT EXISTS role ON membership TYPE string;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON membership TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON membership TYPE datetime;",
		"DEFINE INDEX IF NOT EXISTS membership_organization_role ON membership FIELDS out, role;",
		"DEFINE TABLE IF NOT EXISTS organization_invitation SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS organizationId ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS email ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS role ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS status ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS deliveryStatus ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS lastDeliveryAttemptAt ON organization_invitation TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS lastDeliveryErrorCode ON organization_invitation TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS lastEmailDeliveryId ON organization_invitation TYPE option<string>;",
		"DEFINE FIELD OVERWRITE projectGrants ON organization_invitation TYPE array<object>;",
		"DEFINE FIELD IF NOT EXISTS projectGrants[*].projectId ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectGrants[*].role ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectGrants[*].status ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectGrants[*].createdAt ON organization_invitation TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS projectGrants[*].createdByUserId ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectGrants[*].appliedAt ON organization_invitation TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS invitedByUserId ON organization_invitation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS acceptedByUserId ON organization_invitation TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON organization_invitation TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON organization_invitation TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS acceptedAt ON organization_invitation TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS revokedAt ON organization_invitation TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS expiresAt ON organization_invitation TYPE option<datetime>;",
		"DEFINE INDEX IF NOT EXISTS organization_invitation_org_status ON organization_invitation FIELDS organizationId, status;",
		"DEFINE INDEX IF NOT EXISTS organization_invitation_email_status ON organization_invitation FIELDS organizationId, email, status;",
		"DEFINE INDEX IF NOT EXISTS organization_invitation_delivery_status ON organization_invitation FIELDS deliveryStatus;",
		"DEFINE TABLE IF NOT EXISTS email_delivery SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS kind ON email_delivery TYPE string;",
		"DEFINE FIELD IF NOT EXISTS organizationId ON email_delivery TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectId ON email_delivery TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS invitationId ON email_delivery TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS recipientEmail ON email_delivery TYPE string;",
		"DEFINE FIELD IF NOT EXISTS recipientUserId ON email_delivery TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS template ON email_delivery TYPE string;",
		"DEFINE FIELD IF NOT EXISTS status ON email_delivery TYPE string;",
		"DEFINE FIELD IF NOT EXISTS attemptCount ON email_delivery TYPE int;",
		"DEFINE FIELD IF NOT EXISTS nextAttemptAt ON email_delivery TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS lastAttemptAt ON email_delivery TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS lastErrorCode ON email_delivery TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS subject ON email_delivery TYPE string;",
		"DEFINE FIELD IF NOT EXISTS body ON email_delivery TYPE string;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON email_delivery TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON email_delivery TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS sentAt ON email_delivery TYPE option<datetime>;",
		"DEFINE INDEX IF NOT EXISTS email_delivery_due ON email_delivery FIELDS status, nextAttemptAt;",
		"DEFINE INDEX IF NOT EXISTS email_delivery_invitation ON email_delivery FIELDS invitationId;",
		"DEFINE TABLE IF NOT EXISTS owns_project TYPE RELATION IN organization OUT project SCHEMAFULL;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON owns_project TYPE datetime;",
		"DEFINE TABLE IF NOT EXISTS ingest_credential SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON ingest_credential TYPE string;",
		"DEFINE FIELD IF NOT EXISTS secretHash ON ingest_credential TYPE string;",
		"DEFINE FIELD IF NOT EXISTS displayName ON ingest_credential TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS disabledAt ON ingest_credential TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS lastUsedAt ON ingest_credential TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON ingest_credential TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS createdByUser ON ingest_credential TYPE string;",
		"DEFINE INDEX IF NOT EXISTS ingest_credential_project ON ingest_credential FIELDS projectId;",
		"DEFINE TABLE IF NOT EXISTS dashboard SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS organizationId ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS slug ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS name ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS description ON dashboard TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS tags ON dashboard TYPE array<string>;",
		"DEFINE FIELD IF NOT EXISTS version ON dashboard TYPE int;",
		"DEFINE FIELD IF NOT EXISTS visibility ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS defaultTimeWindow ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS ownerUserId ON dashboard TYPE option<string>;",
		"DEFINE FIELD OVERWRITE widgets ON dashboard TYPE array<object>;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].id ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].title ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].description ON dashboard TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].kind ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].layout ON dashboard TYPE object FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].metric ON dashboard TYPE option<object> FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].richMetric ON dashboard TYPE option<object> FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].logs ON dashboard TYPE option<object> FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].traces ON dashboard TYPE option<object> FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS widgets[*].liveTraces ON dashboard TYPE option<object> FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS searchText ON dashboard TYPE string;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON dashboard TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON dashboard TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS createdBy ON dashboard TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS updatedBy ON dashboard TYPE option<string>;",
		"DEFINE INDEX IF NOT EXISTS dashboard_project ON dashboard FIELDS projectId;",
		"DEFINE INDEX IF NOT EXISTS dashboard_project_visibility ON dashboard FIELDS projectId, visibility;",
		"DEFINE INDEX IF NOT EXISTS dashboard_project_visibility_owner_slug ON dashboard FIELDS projectId, visibility, ownerUserId, slug UNIQUE;",
		"DEFINE INDEX IF NOT EXISTS dashboard_project_search ON dashboard FIELDS projectId, searchText;",
		"DEFINE INDEX IF NOT EXISTS dashboard_project_updated ON dashboard FIELDS projectId, updatedAt;",
		"DEFINE TABLE IF NOT EXISTS dashboard_pin TYPE RELATION IN user OUT dashboard SCHEMAFULL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON dashboard_pin TYPE string;",
		"DEFINE FIELD IF NOT EXISTS position ON dashboard_pin TYPE int;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON dashboard_pin TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON dashboard_pin TYPE datetime;",
		"DEFINE INDEX IF NOT EXISTS dashboard_pin_user_project_position ON dashboard_pin FIELDS in, projectId, position;",
		"DEFINE INDEX IF NOT EXISTS dashboard_pin_user_dashboard_project ON dashboard_pin FIELDS in, out, projectId UNIQUE;",
		"DEFINE TABLE IF NOT EXISTS project_membership SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON project_membership TYPE string;",
		"DEFINE FIELD IF NOT EXISTS userId ON project_membership TYPE string;",
		"DEFINE FIELD IF NOT EXISTS role ON project_membership TYPE string;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON project_membership TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS createdByUserId ON project_membership TYPE string;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON project_membership TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedByUserId ON project_membership TYPE string;",
		"DEFINE INDEX IF NOT EXISTS project_membership_project_user ON project_membership FIELDS projectId, userId UNIQUE;",
		"DEFINE INDEX IF NOT EXISTS project_membership_user ON project_membership FIELDS userId;",
		"DEFINE TABLE IF NOT EXISTS retention_policy SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON retention_policy TYPE string;",
		"DEFINE FIELD OVERWRITE rules ON retention_policy TYPE array<object>;",
		"DEFINE FIELD IF NOT EXISTS rules[*].dataClass ON retention_policy TYPE string;",
		"DEFINE FIELD IF NOT EXISTS rules[*].mode ON retention_policy TYPE string;",
		"DEFINE FIELD IF NOT EXISTS rules[*].retentionDays ON retention_policy TYPE option<int>;",
		"DEFINE FIELD IF NOT EXISTS rules[*].softDeleteDays ON retention_policy TYPE option<int>;",
		"DEFINE FIELD IF NOT EXISTS rules[*].updatedAt ON retention_policy TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS rules[*].updatedByUserId ON retention_policy TYPE string;",
		"DEFINE FIELD IF NOT EXISTS rules[*].version ON retention_policy TYPE int;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON retention_policy TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedByUserId ON retention_policy TYPE string;",
		"DEFINE FIELD IF NOT EXISTS version ON retention_policy TYPE int;",
		"DEFINE INDEX IF NOT EXISTS retention_policy_project ON retention_policy FIELDS projectId UNIQUE;",
		"DEFINE TABLE IF NOT EXISTS project_ai_settings SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON project_ai_settings TYPE string;",
		"DEFINE FIELD OVERWRITE settings ON project_ai_settings TYPE object FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS version ON project_ai_settings TYPE int;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON project_ai_settings TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedByUserId ON project_ai_settings TYPE string;",
		"DEFINE INDEX IF NOT EXISTS project_ai_settings_project ON project_ai_settings FIELDS projectId UNIQUE;",
		"DEFINE TABLE IF NOT EXISTS company_ai_provider_settings SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS companyId ON company_ai_provider_settings TYPE string;",
		"DEFINE FIELD OVERWRITE settings ON company_ai_provider_settings TYPE object FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS version ON company_ai_provider_settings TYPE int;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON company_ai_provider_settings TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedByUserId ON company_ai_provider_settings TYPE string;",
		"DEFINE INDEX IF NOT EXISTS company_ai_provider_settings_company ON company_ai_provider_settings FIELDS companyId UNIQUE;",
		"DEFINE TABLE IF NOT EXISTS ai_provider_secret SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS scope ON ai_provider_secret TYPE string;",
		"DEFINE FIELD IF NOT EXISTS companyId ON ai_provider_secret TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectId ON ai_provider_secret TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS providerId ON ai_provider_secret TYPE string;",
		"DEFINE FIELD IF NOT EXISTS algorithm ON ai_provider_secret TYPE string;",
		"DEFINE FIELD IF NOT EXISTS nonce ON ai_provider_secret TYPE string;",
		"DEFINE FIELD IF NOT EXISTS ciphertext ON ai_provider_secret TYPE string;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON ai_provider_secret TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON ai_provider_secret TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedByUserId ON ai_provider_secret TYPE string;",
		"DEFINE INDEX IF NOT EXISTS ai_provider_secret_company_provider ON ai_provider_secret FIELDS companyId, providerId;",
		"DEFINE INDEX IF NOT EXISTS ai_provider_secret_project_provider ON ai_provider_secret FIELDS projectId, providerId;",
		"DEFINE TABLE IF NOT EXISTS ai_chat_conversation SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS companyId ON ai_chat_conversation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectId ON ai_chat_conversation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS userId ON ai_chat_conversation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS title ON ai_chat_conversation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS status ON ai_chat_conversation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS lastMessageAt ON ai_chat_conversation TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS lastRunStatus ON ai_chat_conversation TYPE string;",
		"DEFINE FIELD IF NOT EXISTS latestCompactionId ON ai_chat_conversation TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON ai_chat_conversation TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON ai_chat_conversation TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS version ON ai_chat_conversation TYPE int;",
		"DEFINE INDEX IF NOT EXISTS ai_chat_conversation_history ON ai_chat_conversation FIELDS companyId, userId, projectId, status, lastMessageAt;",
		"DEFINE TABLE IF NOT EXISTS ai_chat_message SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS conversationId ON ai_chat_message TYPE string;",
		"DEFINE FIELD IF NOT EXISTS runId ON ai_chat_message TYPE string;",
		"DEFINE FIELD IF NOT EXISTS role ON ai_chat_message TYPE string;",
		"DEFINE FIELD OVERWRITE parts ON ai_chat_message TYPE array<object>;",
		"DEFINE FIELD OVERWRITE parts[*] ON ai_chat_message TYPE object FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS tokenEstimate ON ai_chat_message TYPE int;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON ai_chat_message TYPE datetime;",
		"DEFINE INDEX IF NOT EXISTS ai_chat_message_conversation ON ai_chat_message FIELDS conversationId, createdAt;",
		"DEFINE TABLE IF NOT EXISTS ai_chat_run SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS conversationId ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectId ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS userId ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS userMessageClientId ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS idempotencyKey ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS providerKind ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS providerProfileId ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS model ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS status ON ai_chat_run TYPE string;",
		"DEFINE FIELD IF NOT EXISTS traceId ON ai_chat_run TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS toolCallCount ON ai_chat_run TYPE int;",
		"DEFINE FIELD IF NOT EXISTS sandboxScriptCount ON ai_chat_run TYPE int;",
		"DEFINE FIELD IF NOT EXISTS artifactCount ON ai_chat_run TYPE int;",
		"DEFINE FIELD IF NOT EXISTS inputTokenCount ON ai_chat_run TYPE int;",
		"DEFINE FIELD IF NOT EXISTS outputTokenCount ON ai_chat_run TYPE int;",
		"DEFINE FIELD IF NOT EXISTS estimatedCostUsd ON ai_chat_run TYPE option<float>;",
		"DEFINE FIELD IF NOT EXISTS error ON ai_chat_run TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS startedAt ON ai_chat_run TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS completedAt ON ai_chat_run TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON ai_chat_run TYPE datetime;",
		"DEFINE INDEX IF NOT EXISTS ai_chat_run_idempotency ON ai_chat_run FIELDS conversationId, userMessageClientId, idempotencyKey;",
		"DEFINE INDEX IF NOT EXISTS ai_chat_run_active ON ai_chat_run FIELDS conversationId, status, startedAt;",
		"DEFINE TABLE IF NOT EXISTS ai_chat_action SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS conversationId ON ai_chat_action TYPE string;",
		"DEFINE FIELD IF NOT EXISTS runId ON ai_chat_action TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectId ON ai_chat_action TYPE string;",
		"DEFINE FIELD IF NOT EXISTS title ON ai_chat_action TYPE string;",
		"DEFINE FIELD IF NOT EXISTS description ON ai_chat_action TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS risk ON ai_chat_action TYPE string;",
		"DEFINE FIELD IF NOT EXISTS status ON ai_chat_action TYPE string;",
		"DEFINE FIELD IF NOT EXISTS actionKind ON ai_chat_action TYPE string;",
		"DEFINE FIELD IF NOT EXISTS inputPreview ON ai_chat_action TYPE object FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS requiresApproval ON ai_chat_action TYPE bool;",
		"DEFINE FIELD IF NOT EXISTS approvedByUserId ON ai_chat_action TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS approvedAt ON ai_chat_action TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS idempotencyKey ON ai_chat_action TYPE string;",
		"DEFINE FIELD IF NOT EXISTS approvalKey ON ai_chat_action TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS approvalReason ON ai_chat_action TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS expiresAt ON ai_chat_action TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS result ON ai_chat_action TYPE object FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON ai_chat_action TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON ai_chat_action TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS version ON ai_chat_action TYPE int;",
		"DEFINE INDEX IF NOT EXISTS ai_chat_action_conversation ON ai_chat_action FIELDS conversationId, status;",
		"DEFINE TABLE IF NOT EXISTS ai_chat_compaction SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS conversationId ON ai_chat_compaction TYPE string;",
		"DEFINE FIELD IF NOT EXISTS sourceMessageCount ON ai_chat_compaction TYPE int;",
		"DEFINE FIELD IF NOT EXISTS summary ON ai_chat_compaction TYPE string;",
		"DEFINE FIELD IF NOT EXISTS retainedMessageIds ON ai_chat_compaction TYPE array<string>;",
		"DEFINE FIELD IF NOT EXISTS artifactSummaries ON ai_chat_compaction TYPE array<string>;",
		"DEFINE FIELD IF NOT EXISTS pendingActionIds ON ai_chat_compaction TYPE array<string>;",
		"DEFINE FIELD IF NOT EXISTS tokenCount ON ai_chat_compaction TYPE int;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON ai_chat_compaction TYPE datetime;",
		"DEFINE INDEX IF NOT EXISTS ai_chat_compaction_conversation ON ai_chat_compaction FIELDS conversationId, createdAt;",
		"DEFINE TABLE IF NOT EXISTS alert_rule SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON alert_rule TYPE string;",
		"DEFINE FIELD IF NOT EXISTS name ON alert_rule TYPE string;",
		"DEFINE FIELD IF NOT EXISTS enabled ON alert_rule TYPE bool;",
		"DEFINE FIELD IF NOT EXISTS kind ON alert_rule TYPE string;",
		"DEFINE FIELD IF NOT EXISTS severity ON alert_rule TYPE string;",
		"DEFINE FIELD IF NOT EXISTS query ON alert_rule TYPE object FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS condition ON alert_rule TYPE object FLEXIBLE;",
		"DEFINE FIELD IF NOT EXISTS evaluationWindowSeconds ON alert_rule TYPE int;",
		"DEFINE FIELD IF NOT EXISTS pendingForSeconds ON alert_rule TYPE int;",
		"DEFINE FIELD IF NOT EXISTS cooldownSeconds ON alert_rule TYPE int;",
		"DEFINE FIELD IF NOT EXISTS notificationAdapterIds ON alert_rule TYPE array<string>;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON alert_rule TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedAt ON alert_rule TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS updatedByUserId ON alert_rule TYPE string;",
		"DEFINE FIELD IF NOT EXISTS version ON alert_rule TYPE int;",
		"DEFINE INDEX IF NOT EXISTS alert_rule_project ON alert_rule FIELDS projectId;",
		"DEFINE TABLE IF NOT EXISTS alert_silence SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON alert_silence TYPE string;",
		"DEFINE FIELD IF NOT EXISTS ruleId ON alert_silence TYPE string;",
		"DEFINE FIELD IF NOT EXISTS reason ON alert_silence TYPE string;",
		"DEFINE FIELD IF NOT EXISTS startsAt ON alert_silence TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS endsAt ON alert_silence TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON alert_silence TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS createdByUserId ON alert_silence TYPE string;",
		"DEFINE INDEX IF NOT EXISTS alert_silence_project_rule ON alert_silence FIELDS projectId, ruleId;",
		"DEFINE TABLE IF NOT EXISTS alert_event SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS projectId ON alert_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS ruleId ON alert_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS instanceId ON alert_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS state ON alert_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS severity ON alert_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS summary ON alert_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS deduplicationKey ON alert_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS startedAt ON alert_event TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS endedAt ON alert_event TYPE option<datetime>;",
		"DEFINE FIELD IF NOT EXISTS createdAt ON alert_event TYPE datetime;",
		"DEFINE FIELD IF NOT EXISTS evidenceTraceId ON alert_event TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS evidenceSpanId ON alert_event TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS evidenceLogId ON alert_event TYPE option<string>;",
		"DEFINE FIELD IF NOT EXISTS evidenceMetricName ON alert_event TYPE option<string>;",
		"DEFINE INDEX IF NOT EXISTS alert_event_project_rule_created ON alert_event FIELDS projectId, ruleId, createdAt;",
		"DEFINE TABLE IF NOT EXISTS project_status_event SCHEMAFULL TYPE NORMAL PERMISSIONS NONE;",
		"DEFINE FIELD IF NOT EXISTS companyId ON project_status_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS projectId ON project_status_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS status ON project_status_event TYPE string;",
		"DEFINE FIELD IF NOT EXISTS changedAt ON project_status_event TYPE datetime;",
		"DEFINE INDEX IF NOT EXISTS project_status_event_project_changed ON project_status_event FIELDS companyId, projectId, changedAt;",
	}
}

func BuildProjectListQuery(organizationID string, status *contracts.ProjectStatus) (QueryStatement, error) {
	params := map[string]any{}
	conditions := []string{}
	if strings.TrimSpace(organizationID) != "" {
		conditions = append(conditions, "organizationId = $organizationId")
		params["organizationId"] = strings.TrimSpace(organizationID)
	}
	if status != nil {
		conditions = append(conditions, "status = $status")
		params["status"] = string(*status)
	}
	return QueryStatement{
		SQL: strings.Join([]string{
			"SELECT record::id(id) AS ID, organizationId, name, slug, status, changedAt, createdAt, updatedAt",
			"FROM project",
			whereClause(conditions),
			"ORDER BY name ASC, ID ASC;",
		}, " "),
		Params: params,
	}, nil
}

func BuildOrganizationForUserQuery(userID string) QueryStatement {
	return QueryStatement{
		SQL: strings.Join([]string{
			"SELECT record::id(out) AS id, out.name AS name, out.slug AS slug, role",
			"FROM membership",
			"WHERE in = type::record('user', $userId)",
			"ORDER BY name ASC;",
		}, " "),
		Params: map[string]any{"userId": strings.TrimSpace(userID)},
	}
}

func BuildMembershipAdminCountQuery(organizationID string, excludedUserID string) QueryStatement {
	return QueryStatement{
		SQL: strings.Join([]string{
			"SELECT count() AS count",
			"FROM membership",
			"WHERE out = type::record('organization', $organizationId)",
			"AND role = 'admin'",
			"AND in != type::record('user', $excludedUserId)",
			"GROUP ALL;",
		}, " "),
		Params: map[string]any{
			"organizationId": strings.TrimSpace(organizationID),
			"excludedUserId": strings.TrimSpace(excludedUserID),
		},
	}
}

func BuildProjectStatusSnapshotQuery(companyID string, projectID string) QueryStatement {
	return QueryStatement{
		SQL: strings.Join([]string{
			"SELECT organizationId AS companyId, record::id(id) AS projectId, status, changedAt",
			"FROM project",
			"WHERE organizationId = $companyId AND record::id(id) = $projectId",
			"LIMIT 1;",
		}, " "),
		Params: map[string]any{
			"companyId": strings.TrimSpace(companyID),
			"projectId": strings.TrimSpace(projectID),
		},
	}
}

func whereClause(conditions []string) string {
	if len(conditions) == 0 {
		return ""
	}
	return "WHERE " + strings.Join(conditions, " AND ")
}
