import type { DashboardTraceWidget, DashboardTraceWidgetInput } from "@cloudgrid/ui-contracts";

export type {
  Dashboard,
  DashboardAlertWidget,
  DashboardAlertWidgetInput,
  DashboardListInput,
  DashboardListResult,
  DashboardLogColumn,
  DashboardLogWidget,
  DashboardLogWidgetInput,
  DashboardMetricDisplaySeries,
  DashboardMetricDisplaySeriesInput,
  DashboardMetricFormula,
  DashboardMetricFormulaBinaryOperator,
  DashboardMetricFormulaExpression,
  DashboardMetricFormulaExpressionInput,
  DashboardMetricFormulaExpressionKind,
  DashboardMetricFormulaFunction,
  DashboardMetricFormulaInput,
  DashboardMetricQuery,
  DashboardMetricQueryInput,
  DashboardMetricQueryRow,
  DashboardMetricQueryRowInput,
  DashboardMetricWidget,
  DashboardMetricWidgetInput,
  DashboardPreferences,
  DashboardRichMetricWidget,
  DashboardRichMetricWidgetInput,
  DashboardSaveVisibility,
  DashboardThreshold,
  DashboardThresholdInput,
  DashboardThresholdSeverity,
  DashboardTraceColumn,
  DashboardTraceWidget,
  DashboardTraceWidgetInput,
  DashboardVisibility,
  DashboardWidget,
  DashboardWidgetInput,
  DashboardWidgetKind,
  DashboardWidgetLayout,
  DashboardWidgetLayoutInput,
  ReorderDashboardPinsInput,
  RichMetricDisplaySeries,
  RichMetricSeries,
  RichMetricSeriesInput,
  RichMetricSeriesResult,
  SaveDashboardInput,
  SetDashboardPinnedInput,
} from "@cloudgrid/ui-contracts";

export type DashboardLiveTraceWidgetInput = Omit<DashboardTraceWidgetInput, "sort" | "columns">;

export type DashboardLiveTraceWidget = Omit<DashboardTraceWidget, "sort" | "columns">;
