// Code generated by tooling/scripts/generate-contracts.mjs from @cloudgrid/definition; DO NOT EDIT.
package contracts

var DeploymentModes = []string{"local", "deployed"}
var AuthModes = []string{"local", "sso"}
var AuthProviders = []string{"github", "google", "azure"}
var CompanyRoles = []string{"admin", "user"}
var OrganizationInvitationStatuses = []string{"pending", "accepted", "revoked", "expired"}
var InvitationDeliveryStatuses = []string{"not_configured", "pending", "sent", "failed_retryable", "failed_terminal", "suppressed"}
var InvitationProjectGrantStatuses = []string{"pending", "applied", "revoked", "failed"}
var ProjectInvitationOutcomes = []string{"invitation_pending", "membership_created"}
var ProjectRoles = []string{"viewer", "editor", "admin"}
var ProjectMemberSources = []string{"direct", "company_admin", "local_personal"}
var ProjectStatuses = []string{"active", "read_only", "disabled"}
var RetentionDataClasses = []string{"TRACES", "LOGS", "METRICS", "AI_EVALS", "DATASETS", "SCORERS", "DASHBOARD_HISTORY", "INGEST_CREDENTIAL_AUDIT"}
var RetentionModes = []string{"retain", "delete", "soft_delete_then_delete"}
var AlertRuleKinds = []string{"METRIC_THRESHOLD", "METRIC_ABSENCE", "LOG_MATCH", "LOG_COUNT", "TRACE_MATCH", "TRACE_COUNT", "TRACE_LATENCY", "TRACE_ERROR"}
var AlertSeverities = []string{"INFO", "WARNING", "ERROR", "CRITICAL"}
var AlertStates = []string{"OK", "PENDING", "FIRING", "RESOLVED", "SILENCED", "ERROR"}
var AiProviderKinds = []string{"anthropic", "openai", "azure_foundry", "aws_bedrock", "openai_compatible"}
var AiModelPurposes = []string{"default", "chat", "judge", "optimizer", "embedding", "replay"}
var AiChatConversationStatuses = []string{"active", "archived"}
var AiChatRunStatuses = []string{"idle", "queued", "streaming", "completed", "failed", "cancelled", "awaiting_approval"}
var AiChatActionRisks = []string{"low", "medium", "high", "destructive"}
var AiChatActionStatuses = []string{"proposed", "approved", "rejected", "executing", "succeeded", "failed", "expired"}
var AiChatArtifactKinds = []string{"json_render", "data_file", "script", "script_output"}
var AiChatStreamEventTypes = []string{"run.started", "message.created", "text.delta", "tool.started", "tool.completed", "artifact.created", "action.proposed", "compaction.started", "compaction.saved", "run.completed", "run.failed", "heartbeat"}
var ControlPlaneSubjects = []string{"control.viewer.get", "control.organizations.list", "control.organizations.get", "control.projects.list", "control.projects.list_for_service", "control.projects.get", "control.projects.create", "control.projects.update", "control.projects.select", "control.members.list", "control.members.update", "control.members.remove", "control.invitations.list", "control.invitations.create", "control.invitations.resend", "control.invitations.revoke", "control.project_invitations.create", "control.ingest_credentials.list", "control.ingest_credentials.create", "control.ingest_credentials.revoke", "control.ai_settings.get", "control.ai_settings.update", "control.ai_providers.project.get", "control.ai_providers.project.update", "control.ai_providers.company.get", "control.ai_providers.company.update", "control.ai_provider_secrets.resolve", "control.ai_chat.history", "control.ai_chat.conversation.get", "control.ai_chat.conversation.create", "control.ai_chat.conversation.archive", "control.ai_chat.conversation.delete", "control.ai_chat.message.append", "control.ai_chat.run.create", "control.ai_chat.run.update", "control.ai_chat.run.finalize", "control.ai_chat.action.propose", "control.ai_chat.action.approve", "control.ai_chat.action.finish", "control.ai_chat.compaction.save", "control.project_status.snapshot", "control.project_status.changed", "control.dashboards.list", "control.dashboards.save", "control.dashboards.delete", "control.dashboard_pins.set", "control.dashboard_pins.reorder", "control.project_members.list", "control.project_members.update", "control.project_members.remove", "control.retention.get", "control.retention.update", "control.alert_rules.list", "control.alert_rules.create", "control.alert_rules.update", "control.alert_rules.delete", "control.alert_silences.list", "control.alert_silences.create", "control.alert_silences.delete", "control.alert_history.list", "control.alert_summary.get", "control.alert_history.record"}
var StorageMaintenanceSubjects = []string{"storage_maintenance.retention.execute_batch"}
var AlertEvaluatorSubjects = []string{"alert_evaluator.tick", "alert_evaluator.rules.evaluate", "alert_evaluator.notifications.dispatch"}
var AiEvalSubjects = []string{"telemetry.ingest.ai_projections", "ai.persisted.projections", "eval.dataset.create", "eval.dataset.search", "eval.dataset.items.append", "eval.dataset.item.promote", "eval.dataset.import.prepare", "eval.dataset.import.commit", "eval.dataset.export.start", "eval.dataset.transfer.get", "eval.dataset.health", "eval.agent_runs.search", "eval.scorer.create", "eval.scorer.search", "eval.experiment.create", "eval.experiment.start", "eval.experiment.cancel", "eval.optimization.start", "eval.experiment.search", "eval.results.search", "eval.results.persist", "eval.online.policy_matches.resolve", "eval.live.start", "eval.live.stop", "eval.live.events.*.*", "eval.experiment.progress", "eval.manifest.resolve", "eval.quality.overview", "eval.prompt_version.promote", "annotation.queue.search", "annotation.item.update"}
