// Code generated by tooling/scripts/generate-contracts.mjs from @cloudgrid/definition; DO NOT EDIT.
package contracts

var DeploymentModes = []string{"local", "deployed"}
var AuthModes = []string{"local", "sso"}
var AuthProviders = []string{"github", "google", "azure"}
var CompanyRoles = []string{"admin", "user"}
var OrganizationInvitationStatuses = []string{"pending", "accepted", "revoked", "expired"}
var ProjectRoles = []string{"viewer", "editor", "admin"}
var ProjectMemberSources = []string{"direct", "company_admin", "local_personal"}
var ProjectStatuses = []string{"active", "read_only", "disabled"}
var RetentionDataClasses = []string{"TRACES", "LOGS", "METRICS", "AI_EVALS", "DATASETS", "SCORERS", "DASHBOARD_HISTORY", "INGEST_CREDENTIAL_AUDIT"}
var RetentionModes = []string{"retain", "delete", "soft_delete_then_delete"}
var AlertRuleKinds = []string{"METRIC_THRESHOLD", "METRIC_ABSENCE", "LOG_MATCH", "LOG_COUNT", "TRACE_MATCH", "TRACE_COUNT", "TRACE_LATENCY", "TRACE_ERROR"}
var AlertSeverities = []string{"INFO", "WARNING", "ERROR", "CRITICAL"}
var AlertStates = []string{"OK", "PENDING", "FIRING", "RESOLVED", "SILENCED", "ERROR"}
var ControlPlaneSubjects = []string{"control.viewer.get", "control.organizations.list", "control.organizations.get", "control.projects.list", "control.projects.get", "control.projects.create", "control.projects.update", "control.projects.select", "control.members.list", "control.members.update", "control.members.remove", "control.invitations.list", "control.invitations.create", "control.invitations.revoke", "control.ingest_credentials.list", "control.ingest_credentials.create", "control.ingest_credentials.revoke", "control.ai_settings.get", "control.ai_settings.update", "control.project_status.snapshot", "control.project_status.changed", "control.dashboards.list", "control.dashboards.save", "control.dashboards.delete", "control.dashboard_pins.set", "control.dashboard_pins.reorder", "control.project_members.list", "control.project_members.update", "control.project_members.remove", "control.retention.get", "control.retention.update", "control.alert_rules.list", "control.alert_rules.create", "control.alert_rules.update", "control.alert_rules.delete", "control.alert_silences.list", "control.alert_silences.create", "control.alert_silences.delete", "control.alert_history.list", "control.alert_history.record"}
var StorageMaintenanceSubjects = []string{"storage_maintenance.retention.execute_batch"}
var AlertEvaluatorSubjects = []string{"alert_evaluator.tick", "alert_evaluator.rules.evaluate", "alert_evaluator.notifications.dispatch"}
var AiEvalSubjects = []string{"telemetry.ingest.ai_projections", "ai.persisted.projections", "eval.dataset.create", "eval.dataset.search", "eval.dataset.items.append", "eval.dataset.item.promote", "eval.dataset.health", "eval.agent_runs.search", "eval.scorer.create", "eval.scorer.search", "eval.experiment.create", "eval.experiment.start", "eval.experiment.cancel", "eval.optimization.start", "eval.experiment.search", "eval.results.search", "eval.results.persist", "eval.live.start", "eval.live.stop", "eval.live.events.*.*", "eval.experiment.progress", "eval.manifest.resolve", "eval.quality.overview", "eval.prompt_version.promote", "annotation.queue.search", "annotation.item.update"}
